name: Docker CI

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ['build']
    types:
      - completed
    
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Install modules
        run: yarn
      -
        name: Launch tests
        run: yarn test

  build:
    name: Build and push
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: benjaminvimeux/docker-todo-app:latest